import { tryRecordAudit } from '../auditService';
import type { UserRow } from '../columns';
import { authorize, type OperationContext } from '../context';
import {
  currentSessionUserId,
  db,
  mapWithConcurrency,
  MAX_ROWS,
  withRelationships,
  withRetry,
} from '../dataUtils';

import { generateDemoDataset } from './generator';

const WRITE_CONCURRENCY = 16;

export interface SeedProgress {
  phase: string;
  done: number;
  total: number;
  overallDone: number;
  overallTotal: number;
}

export type SeedProgressHandler = (progress: SeedProgress) => void;

export interface SeedResult {
  customers: number;
  vendors: number;
  invoices: number;
  payments: number;
  exceptions: number;
  records: number;
}

/** True when the demo dataset has not been loaded into this database yet. */
export async function isDatabaseEmpty(): Promise<boolean> {
  const rows = await db().Customer.select(['id']).first(1).execute();
  return rows.length === 0;
}

/**
 * Write the synthetic dataset.
 *
 * Records are written in dependency order because primary keys are generated by
 * the database, and each phase fans out with a bounded number of concurrent
 * mutations. Nothing here contacts an external system — every row is invented
 * locally by `generateDemoDataset`.
 */
export async function seedDemoData(
  onProgress?: SeedProgressHandler
): Promise<SeedResult> {
  const data = generateDemoDataset();
  const client = db();
  const sessionUserId = currentSessionUserId();

  const overallTotal =
    data.exceptionCategories.length +
    data.resolutionCategories.length +
    data.slaRules.length +
    data.methodRules.length +
    data.users.length +
    data.customers.length +
    data.vendors.length +
    data.invoices.length +
    data.payments.length +
    data.attempts.length +
    data.approvals.length +
    data.exceptions.length +
    data.assignments.length +
    data.notes.length +
    data.history.length +
    data.metrics.length;

  let overallDone = 0;

  const report = (phase: string) => (done: number, total: number) => {
    onProgress?.({
      phase,
      done,
      total,
      overallDone: overallDone + done,
      overallTotal,
    });
  };

  async function phase<T, R>(
    label: string,
    items: readonly T[],
    worker: (item: T, index: number) => Promise<R>
  ): Promise<R[]> {
    onProgress?.({
      phase: label,
      done: 0,
      total: items.length,
      overallDone,
      overallTotal,
    });
    const results = await mapWithConcurrency(
      items,
      WRITE_CONCURRENCY,
      (item, index) => withRetry(() => worker(item, index)),
      report(label)
    );
    overallDone += items.length;
    return results;
  }

  /* 1 — configuration */
  await phase('Exception categories', data.exceptionCategories, (c) =>
    client.ExceptionCategory.create({ ...c })
  );
  const resolutionRows = await phase(
    'Resolution categories',
    data.resolutionCategories,
    (c) => client.ResolutionCategory.create({ ...c })
  );
  await phase('Service level targets', data.slaRules, (r) =>
    client.ServiceLevelRule.create({ ...r })
  );
  await phase('Payment method rules', data.methodRules, (r) =>
    client.PaymentMethodRule.create({ ...r })
  );

  /* 2 — people */
  const userIds = new Map<string, string>();
  const userRows = await phase('Operators', data.users, async (u) => {
    const { key, ...fields } = u;
    const created = await client.AppUser.create(fields);
    userIds.set(key, created.id);
    return created as UserRow;
  });

  /* 3 — parties */
  const customerIds = new Map<string, string>();
  await phase('Customers', data.customers, async (c) => {
    const { key, ...fields } = c;
    const created = await client.Customer.create(fields);
    customerIds.set(key, created.id);
  });

  const vendorIds = new Map<string, string>();
  await phase('Vendors', data.vendors, async (v) => {
    const { key, ...fields } = v;
    const created = await client.Vendor.create(fields);
    vendorIds.set(key, created.id);
  });

  /* 4 — invoices */
  const invoiceIds = new Map<string, string>();
  await phase('Invoices', data.invoices, async (inv) => {
    const { key, customerKey, vendorKey, ...fields } = inv;
    const created = await client.Invoice.create(
      withRelationships(fields, [], {
        customer: { id: customerIds.get(customerKey)! },
        vendor: { id: vendorIds.get(vendorKey)! },
      })
    );
    invoiceIds.set(key, created.id);
  });

  /* 5 — payments */
  const paymentIds = new Map<string, string>();
  await phase('Payments', data.payments, async (p) => {
    const { key, invoiceKey, customerKey, vendorKey, ...fields } = p;
    const created = await client.Payment.create(
      withRelationships(fields, [], {
        invoice: { id: invoiceIds.get(invoiceKey)! },
        customer: { id: customerIds.get(customerKey)! },
        vendor: { id: vendorIds.get(vendorKey)! },
      })
    );
    paymentIds.set(key, created.id);
  });

  await phase('Payment attempts', data.attempts, async (a) => {
    const { paymentKey, ...fields } = a;
    await client.PaymentAttempt.create(
      withRelationships(fields, [], {
        payment: { id: paymentIds.get(paymentKey)! },
      })
    );
  });

  await phase('Approval history', data.approvals, async (a) => {
    const { invoiceKey, ...fields } = a;
    await client.ApprovalEvent.create(
      withRelationships(fields, [], {
        invoice: { id: invoiceIds.get(invoiceKey)! },
      })
    );
  });

  /* 6 — exceptions and their trail */
  const exceptionIds = new Map<string, string>();
  await phase('Exceptions', data.exceptions, async (e) => {
    const {
      key,
      customerKey,
      vendorKey,
      invoiceKey,
      paymentKey,
      assigneeKey,
      ...fields
    } = e;
    const created = await client.PaymentException.create(
      withRelationships(fields, [], {
        customer: { id: customerIds.get(customerKey)! },
        vendor: vendorKey ? { id: vendorIds.get(vendorKey)! } : undefined,
        invoice: invoiceKey ? { id: invoiceIds.get(invoiceKey)! } : undefined,
        payment: paymentKey ? { id: paymentIds.get(paymentKey)! } : undefined,
        assignedTo: assigneeKey ? { id: userIds.get(assigneeKey)! } : undefined,
        resolutionCategory:
          fields.status === 'resolved' || fields.status === 'closed'
            ? { id: resolutionRows[0].id }
            : undefined,
      })
    );
    exceptionIds.set(key, created.id);
  });

  await phase('Assignments', data.assignments, async (a) => {
    const { exceptionKey, assigneeKey, ...fields } = a;
    await client.ExceptionAssignment.create(
      withRelationships(
        { ...fields, assigned_by_user_id: sessionUserId },
        [],
        {
          exception: { id: exceptionIds.get(exceptionKey)! },
          assignedTo: { id: userIds.get(assigneeKey)! },
        }
      )
    );
  });

  await phase('Notes', data.notes, async (n) => {
    const { exceptionKey, customerKey, vendorKey, ...fields } = n;
    await client.ExceptionNote.create(
      withRelationships({ ...fields, author_user_id: sessionUserId }, [], {
        exception: exceptionKey
          ? { id: exceptionIds.get(exceptionKey)! }
          : undefined,
        customer: customerKey ? { id: customerIds.get(customerKey)! } : undefined,
        vendor: vendorKey ? { id: vendorIds.get(vendorKey)! } : undefined,
      })
    );
  });

  await phase('Status history', data.history, async (h) => {
    const { exceptionKey, ...fields } = h;
    await client.ExceptionStatusHistory.create(
      withRelationships({ ...fields, changed_by_user_id: sessionUserId }, [], {
        exception: { id: exceptionIds.get(exceptionKey)! },
      })
    );
  });

  /* 7 — pre-aggregated daily figures */
  await phase('Daily metrics', data.metrics, (m) =>
    client.DailyOperationalMetric.create({ ...m })
  );

  return {
    customers: data.customers.length,
    vendors: data.vendors.length,
    invoices: data.invoices.length,
    payments: data.payments.length,
    exceptions: data.exceptions.length,
    records: overallTotal + userRows.length * 0,
  };
}

/**
 * Delete every demo row so the dataset can be regenerated.
 *
 * `AuditEvent` and `AppUser` are deliberately left in place: the audit trail is
 * append-only at the API layer and survives a demo reset, which is exactly the
 * behaviour an auditor should be able to verify.
 */
export async function resetDemoData(
  ctx: OperationContext,
  onProgress?: SeedProgressHandler
): Promise<void> {
  authorize(ctx, 'admin.resetDemoData');
  const client = db();

  const steps: { label: string; run: () => Promise<{ id: string }[]>; del: (id: string) => Promise<unknown> }[] = [
    {
      label: 'Status history',
      run: () => client.ExceptionStatusHistory.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ExceptionStatusHistory.delete({ id }),
    },
    {
      label: 'Notes',
      run: () => client.ExceptionNote.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ExceptionNote.delete({ id }),
    },
    {
      label: 'Assignments',
      run: () => client.ExceptionAssignment.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ExceptionAssignment.delete({ id }),
    },
    {
      label: 'Exceptions',
      run: () => client.PaymentException.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.PaymentException.delete({ id }),
    },
    {
      label: 'Payment attempts',
      run: () => client.PaymentAttempt.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.PaymentAttempt.delete({ id }),
    },
    {
      label: 'Approval history',
      run: () => client.ApprovalEvent.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ApprovalEvent.delete({ id }),
    },
    {
      label: 'Payments',
      run: () => client.Payment.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.Payment.delete({ id }),
    },
    {
      label: 'Invoices',
      run: () => client.Invoice.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.Invoice.delete({ id }),
    },
    {
      label: 'Vendors',
      run: () => client.Vendor.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.Vendor.delete({ id }),
    },
    {
      label: 'Customers',
      run: () => client.Customer.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.Customer.delete({ id }),
    },
    {
      label: 'Daily metrics',
      run: () => client.DailyOperationalMetric.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.DailyOperationalMetric.delete({ id }),
    },
    {
      label: 'Exception categories',
      run: () => client.ExceptionCategory.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ExceptionCategory.delete({ id }),
    },
    {
      label: 'Resolution categories',
      run: () => client.ResolutionCategory.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ResolutionCategory.delete({ id }),
    },
    {
      label: 'Service level targets',
      run: () => client.ServiceLevelRule.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.ServiceLevelRule.delete({ id }),
    },
    {
      label: 'Payment method rules',
      run: () => client.PaymentMethodRule.select(['id']).first(MAX_ROWS).execute(),
      del: (id) => client.PaymentMethodRule.delete({ id }),
    },
  ];

  for (const step of steps) {
    const rows = await step.run();
    onProgress?.({
      phase: `Clearing ${step.label.toLowerCase()}`,
      done: 0,
      total: rows.length,
      overallDone: 0,
      overallTotal: rows.length,
    });
    await mapWithConcurrency(
      rows,
      WRITE_CONCURRENCY,
      (row) => withRetry(() => step.del(row.id)),
      (done, total) =>
        onProgress?.({
          phase: `Clearing ${step.label.toLowerCase()}`,
          done,
          total,
          overallDone: done,
          overallTotal: total,
        })
    );
  }

  await tryRecordAudit(ctx.actor, {
    entityType: 'System',
    entityId: 'demo-data',
    entityLabel: 'Demo dataset',
    action: 'demo-data-reset',
    explanation: 'Demo data cleared from the Administration page.',
  });
}
